service: bringjal
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: dev
  timeout: 15 

functions:
  hello:
    handler: handler.hello
    events:
     - http: ANY /{proxy+}
     - http: ANY /
    environment:
     ATLAS_URI: mongodb+srv://deepakshukla7274:deepak7274@mongo.dlzgbyq.mongodb.net/delivery_db?retryWrites=true&w=majority
     JWT_SECRET: somesuperhardstringtofindout
     PORT: 8000
     GOOGLE_API_KEY: AIzaSyDgs82c1GlN8j7ADTgQAnWUtH3oo-83i9U

